### ISSUE TITLE
Put more things on front page

### ISSUE THREAD

**Issue by jcwang111** [QC-UCI/qc-uci.club#83]
Maybe put interesting projects and events, or info like meeting time on the front page so people looking for our quantum computing club can see it when they land. Or add a banner to make it look more interesting.

edited below:
**TODO**
- [x]  #86 
- [x] add featured projects
- [x] add features events
- [ ] add regular meeting time

**Comment by omarcostahamido** [comment]
I remember having some discussion about redesigning the front page.
for example it would be cool to have the video play automatically (muted).

what would the banner you're proposing be like?
to have the meeting time there immediately available also sounds like a good idea.

I can see now that you've already done some updates on the whole website here https://github.com/QC-UCI/qc-uci.club/commit/c3edfdd7fa56c51b0fc2cc96b9850e59d2f96e6c
So, I guess you would be happy to take on this front page redesign (?)

**Comment by jcwang111** [comment]
Oh yeah I'm planning to work on it when I find time. Just putting this issue up as a note on what to work on for the future lol

**Comment by dssikdar** [comment]
Right now, I have put two pictures below the header. But, it would be nice to create some sort of slide show. In some website I have visited previously, the main image would be changing every 10 seconds and rotating through a list of 4-5 photos.

**Comment by omarcostahamido** [comment]
It seems that #86 is a sub-issue of this.
I'll edit the OP to include a TODO and make it a meta-issue

**Comment by dssikdar** [comment]
For the meeting date and time, which section do we want it to be in the updated page? I was thinking either below the "Quantum Computing at UCI" title in a colored text box or in the "What We Do" section...

**Comment by omarcostahamido** [comment]
Hi @dssikdar just to let you know that I am going to let you run it now, and I hope to see other ppl interacting with this repo now too... and resolve the pending issues/pr. If you need my specific attention or help for something, please tag me using @omarcostahamido 
Best,
OCH

**Comment by dssikdar** [comment]
Ok, thank you so much for your help. Greatly appreciated! :) 
~ Diptanshu
